version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.0.3
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net

  setup-resources:
    image: mesosphere/aws-cli:1.14.5
    volumes:
      - ./:/project
    environment:
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    # command: /project/setup-resources.sh # uncomment this line to run the setup queues script
    networks:
      - localstack-net
    depends_on:
      - localstack

networks:
  localstack-net:
    driver: bridge
