apiVersion: v1
kind: Service
metadata:
  name: k8s-tilt-dev-example-node-nestjs-app-service
spec:
  selector:
    app: k8s-tilt-dev-example
    tier: node-nestjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
