apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tilt-dev-example-node-nestjs-api-deployment
spec:
  selector:
    matchLabels:
      app: k8s-tilt-dev-example
      tier: node-nestjs-api
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-tilt-dev-example
        tier: node-nestjs-api
    spec:
      containers:
        - name: k8s-tilt-dev-example-node-nestjs-api
          image: k8s-tilt-dev-example-express-node-nestjs-api
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
