apiVersion: v1
kind: Service
metadata:
  name: k8s-tilt-dev-example-node-nestjs-api-service
spec:
  selector:
    app: k8s-tilt-dev-example
    tier: node-nestjs-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
