version: '3'

services:
  nginx:
    image: nginx:alpine3.18-slim
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  wordpress:
    image: wordpress:6.3.1-php8.2
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11.0.3
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db-data:
