service: ${env:SERVICE_NAME, 'CognitoLocalLambdas'}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  preSignUp:
    handler: src/handlers/handler.preSignUp
    events:
      - cognitoUserPool:
          pool: ${env:COGNITO_POOL_NAME, 'MyUserPool'}
          trigger: PreSignUp

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 4000

