apiVersion: v1
kind: Service
metadata:
  name: k8s-tilt-dev-example-python-fastapi-app-service
spec:
  selector:
    app: k8s-tilt-dev-example
    tier: python-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
