version: "3.9"

services:
  mssql:
    container_name: mssql
    build:
      context: .
      dockerfile: ./mssql.Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - mssql-data:/var/lib/mssqlql/data
      - ./initdb.d:/opt/mssql-scripts:ro
    ports:
      - 1433:1433
    networks:
      - mssql-net

networks:
  mssql-net:
    driver: bridge

volumes:
  mssql-data:
    name: mssql-data
