service: serverless-fastapi-example

package:
  individually: true

useDotenv: true

provider:
  name: aws
  profile: ${opt:aws-profile, "default"}
  region: ${opt:region, "us-east-2"}
  stage: ${opt:stage, "staging"}
  runtime: python3.9
  memorySize: 128
  timeout: 30
  #iam:
  #  role: ${opt:iamrole}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: serverless-fastapi-example
      description: serverless-fastapi-example API Layer
      compatibleRuntimes:
        - python3.9

functions:
  app:
    package:
      patterns:
        - 'src/**'
        - 'env.providers.json'
        - '!requirements.txt'
        - '!requirements.dev.txt'
        - '!README.md'
        - '!setup.cfg'
        - '!package.json'
        - '!package-lock.json'
        - '!.serverless/**'
        - '!venv/**'
        - '!node_modules/**'
    handler: src/main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /docs
          method: ANY
          private: false
      - http:
          path: /openapi.json
          method: ANY
          private: false
